//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.Content {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursoMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoMaster() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.Content.RecursoMaster", typeof(RecursoMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Login.aspx.
        /// </summary>
        public static string addressLogin {
            get {
                return ResourceManager.GetString("addressLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a img.
        /// </summary>
        public static string imgTag {
            get {
                return ResourceManager.GetString("imgTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a link.
        /// </summary>
        public static string linkTag {
            get {
                return ResourceManager.GetString("linkTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre.
        /// </summary>
        public static string nameTag {
            get {
                return ResourceManager.GetString("nameTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rol.
        /// </summary>
        public static string rolTag {
            get {
                return ResourceManager.GetString("rolTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lastname.
        /// </summary>
        public static string sessionLastname {
            get {
                return ResourceManager.GetString("sessionLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string sessionName {
            get {
                return ResourceManager.GetString("sessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        public static string sessionRol {
            get {
                return ResourceManager.GetString("sessionRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a userID.
        /// </summary>
        public static string sessionUserID {
            get {
                return ResourceManager.GetString("sessionUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UserName.
        /// </summary>
        public static string sessionUserName {
            get {
                return ResourceManager.GetString("sessionUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -.
        /// </summary>
        public static string splitRoles {
            get {
                return ResourceManager.GetString("splitRoles", resourceCulture);
            }
        }
    }
}
