//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FondaResources.OrderAccount {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FondaResources.OrderAccount.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CommandCloseOrder.
        /// </summary>
        public static string ClassNameCloseOrder {
            get {
                return ResourceManager.GetString("ClassNameCloseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CommandGenerateInvoice.
        /// </summary>
        public static string ClassNameGenerateInvoice {
            get {
                return ResourceManager.GetString("ClassNameGenerateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CommandGetCloseOrders.
        /// </summary>
        public static string ClassNameGetCloseOrders {
            get {
                return ResourceManager.GetString("ClassNameGetCloseOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CommandGetInvoice.
        /// </summary>
        public static string ClassNameGetInvoice {
            get {
                return ResourceManager.GetString("ClassNameGetInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CommandGetOrder.
        /// </summary>
        public static string ClassNameGetOrder {
            get {
                return ResourceManager.GetString("ClassNameGetOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CommandGetOrders.
        /// </summary>
        public static string ClassNameGetOrders {
            get {
                return ResourceManager.GetString("ClassNameGetOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CommandPayOrder.
        /// </summary>
        public static string ClassNamePayOrder {
            get {
                return ResourceManager.GetString("ClassNamePayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execute.
        /// </summary>
        public static string CommandMethod {
            get {
                return ResourceManager.GetString("CommandMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear la factura para una orden cerrada.
        /// </summary>
        public static string ErrorMessageGenerateInvoice {
            get {
                return ResourceManager.GetString("ErrorMessageGenerateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error obteniendo las ordenes cerradas de un Restaurante.
        /// </summary>
        public static string ErrorMessageGetCloseOrders {
            get {
                return ResourceManager.GetString("ErrorMessageGetCloseOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener la factura de una orden cerrada.
        /// </summary>
        public static string ErrorMessageGetInvoice {
            get {
                return ResourceManager.GetString("ErrorMessageGetInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener una orden.
        /// </summary>
        public static string ErrorMessageGetOrder {
            get {
                return ResourceManager.GetString("ErrorMessageGetOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error obteniendo las ordenes de un Restaurante.
        /// </summary>
        public static string ErrorMessageGetOrders {
            get {
                return ResourceManager.GetString("ErrorMessageGetOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al pagar una orden abierta en un Restaurante.
        /// </summary>
        public static string ErrorMessagePayOrder {
            get {
                return ResourceManager.GetString("ErrorMessagePayOrder", resourceCulture);
            }
        }
    }
}
