//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FondaResources.OrderAccount {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FondaResources.OrderAccount.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command CancelInvoice.
        /// </summary>
        public static string ClassNameCancelInvoice {
            get {
                return ResourceManager.GetString("ClassNameCancelInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandCloseCashRegister.
        /// </summary>
        public static string ClassNameCloseCashRegister {
            get {
                return ResourceManager.GetString("ClassNameCloseCashRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClosedOrdersPresenter.
        /// </summary>
        public static string ClassNameClosedOrdersPresenter {
            get {
                return ResourceManager.GetString("ClassNameClosedOrdersPresenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandCloseOrder.
        /// </summary>
        public static string ClassNameCloseOrder {
            get {
                return ResourceManager.GetString("ClassNameCloseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DetailOrderPresenter.
        /// </summary>
        public static string ClassNameDetailOrderPresenter {
            get {
                return ResourceManager.GetString("ClassNameDetailOrderPresenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandFindInvoicesByAccount.
        /// </summary>
        public static string ClassNameFindInvoicesByAccount {
            get {
                return ResourceManager.GetString("ClassNameFindInvoicesByAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandFindInvoicesByRestaurant.
        /// </summary>
        public static string ClassNameFindInvoicesByRestaurant {
            get {
                return ResourceManager.GetString("ClassNameFindInvoicesByRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandGenerateInvoice.
        /// </summary>
        public static string ClassNameGenerateInvoice {
            get {
                return ResourceManager.GetString("ClassNameGenerateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandGetCloseOrders.
        /// </summary>
        public static string ClassNameGetCloseOrders {
            get {
                return ResourceManager.GetString("ClassNameGetCloseOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandGetCurrencyByRestaurant.
        /// </summary>
        public static string ClassNameGetCurrencyByRestaurant {
            get {
                return ResourceManager.GetString("ClassNameGetCurrencyByRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandGetDetailOrder.
        /// </summary>
        public static string ClassNameGetDetailOrder {
            get {
                return ResourceManager.GetString("ClassNameGetDetailOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandGetDishOrdersByAccount.
        /// </summary>
        public static string ClassNameGetDishOrdersByAccount {
            get {
                return ResourceManager.GetString("ClassNameGetDishOrdersByAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandGetGenerateInvoice.
        /// </summary>
        public static string ClassNameGetGenerateInvoice {
            get {
                return ResourceManager.GetString("ClassNameGetGenerateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandGetInvoice.
        /// </summary>
        public static string ClassNameGetInvoice {
            get {
                return ResourceManager.GetString("ClassNameGetInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandGetOrder.
        /// </summary>
        public static string ClassNameGetOrder {
            get {
                return ResourceManager.GetString("ClassNameGetOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandGetOrders.
        /// </summary>
        public static string ClassNameGetOrders {
            get {
                return ResourceManager.GetString("ClassNameGetOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderInvoicesPresenter.
        /// </summary>
        public static string ClassNameOrderInvoicesPresenter {
            get {
                return ResourceManager.GetString("ClassNameOrderInvoicesPresenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrdersPresenter.
        /// </summary>
        public static string ClassNameOrdersPresenter {
            get {
                return ResourceManager.GetString("ClassNameOrdersPresenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandPayOrder.
        /// </summary>
        public static string ClassNamePayOrder {
            get {
                return ResourceManager.GetString("ClassNamePayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandReleaseTableByRestaurant.
        /// </summary>
        public static string ClassNameReleaseTableByRestaurant {
            get {
                return ResourceManager.GetString("ClassNameReleaseTableByRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandTotalOrder.
        /// </summary>
        public static string ClassNameTotalOrder {
            get {
                return ResourceManager.GetString("ClassNameTotalOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al realizar el cierre de caja.
        /// </summary>
        public static string ErrorMessageCloseCashRegister {
            get {
                return ResourceManager.GetString("ErrorMessageCloseCashRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear la factura para una orden cerrada.
        /// </summary>
        public static string ErrorMessageGenerateInvoice {
            get {
                return ResourceManager.GetString("ErrorMessageGenerateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error obteniendo las ordenes cerradas de un Restaurante.
        /// </summary>
        public static string ErrorMessageGetCloseOrders {
            get {
                return ResourceManager.GetString("ErrorMessageGetCloseOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener la factura de una orden cerrada.
        /// </summary>
        public static string ErrorMessageGetInvoice {
            get {
                return ResourceManager.GetString("ErrorMessageGetInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener una orden.
        /// </summary>
        public static string ErrorMessageGetOrder {
            get {
                return ResourceManager.GetString("ErrorMessageGetOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error obteniendo las ordenes de un Restaurante.
        /// </summary>
        public static string ErrorMessageGetOrders {
            get {
                return ResourceManager.GetString("ErrorMessageGetOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al pagar una orden abierta en un Restaurante.
        /// </summary>
        public static string ErrorMessagePayOrder {
            get {
                return ResourceManager.GetString("ErrorMessagePayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede realizar el cierre de caja cuando existen ordenes abiertas.
        /// </summary>
        public static string MessageMVPExceptionCloseButton {
            get {
                return ResourceManager.GetString("MessageMVPExceptionCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al llenar la tabla de Ordenes cerradas.
        /// </summary>
        public static string MessageMVPExceptionClosedOrdersTable {
            get {
                return ResourceManager.GetString("MessageMVPExceptionClosedOrdersTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al llenar la tabla del detale de la Orden #.
        /// </summary>
        public static string MessageMVPExceptionDetailOrderTable {
            get {
                return ResourceManager.GetString("MessageMVPExceptionDetailOrderTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al llenar la tabla de Facturas.
        /// </summary>
        public static string MessageMVPExceptionOrderInvoicesTable {
            get {
                return ResourceManager.GetString("MessageMVPExceptionOrderInvoicesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al llenar la tabla de Ordenes abiertas.
        /// </summary>
        public static string MessageMVPExceptionOrdersTable {
            get {
                return ResourceManager.GetString("MessageMVPExceptionOrdersTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al realizar el casteo del URL.
        /// </summary>
        public static string MessageMVPExceptionQuery {
            get {
                return ResourceManager.GetString("MessageMVPExceptionQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BO-04-005.
        /// </summary>
        public static string MVPExceptionCloseButtonCode {
            get {
                return ResourceManager.GetString("MVPExceptionCloseButtonCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BO-04-001.
        /// </summary>
        public static string MVPExceptionClosedOrdersTableCode {
            get {
                return ResourceManager.GetString("MVPExceptionClosedOrdersTableCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BO-04-004.
        /// </summary>
        public static string MVPExceptionDetailOrderTableCode {
            get {
                return ResourceManager.GetString("MVPExceptionDetailOrderTableCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BO-04-003.
        /// </summary>
        public static string MVPExceptionOrderInvoicesTableCode {
            get {
                return ResourceManager.GetString("MVPExceptionOrderInvoicesTableCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BO-04-002.
        /// </summary>
        public static string MVPExceptionOrdersTableCode {
            get {
                return ResourceManager.GetString("MVPExceptionOrdersTableCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BO-04-006.
        /// </summary>
        public static string MVPExceptionQueryCode {
            get {
                return ResourceManager.GetString("MVPExceptionQueryCode", resourceCulture);
            }
        }
    }
}
