//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FondaResources.OrderAccount {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderAccountResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderAccountResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FondaResources.OrderAccount.OrderAccountResources", typeof(OrderAccountResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string ActionColumn {
            get {
                return ResourceManager.GetString("ActionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-info-circle&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string ActionInfo {
            get {
                return ResourceManager.GetString("ActionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-money fa-fw&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string ActionInvoices {
            get {
                return ResourceManager.GetString("ActionInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-danger&quot;&gt;&lt;i class=&quot;fa fa-times&quot;&gt;&lt;p class=&quot;stat&quot;&gt;I&lt;/p&gt;&lt;/i&gt;&lt;/span&gt;.
        /// </summary>
        public static string CanceledStatus {
            get {
                return ResourceManager.GetString("CanceledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CashPayment.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClosedOrdersPresenter.
        /// </summary>
        public static string ClassNameClosedOrdersPresenter {
            get {
                return ResourceManager.GetString("ClassNameClosedOrdersPresenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditCardPayment.
        /// </summary>
        public static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data-id.
        /// </summary>
        public static string dataId {
            get {
                return ResourceManager.GetString("dataId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string DateColumn {
            get {
                return ResourceManager.GetString("DateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Caja/VerDetalleOrden.aspx?Id=.
        /// </summary>
        public static string detailURL {
            get {
                return ResourceManager.GetString("detailURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Platillo.
        /// </summary>
        public static string DishNameColum {
            get {
                return ResourceManager.GetString("DishNameColum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-success&quot;&gt;&lt;i class=&quot;fa fa-check&quot;&gt;&lt;p class=&quot;stat&quot;&gt;A&lt;/p&gt;&lt;/i&gt;&lt;/span&gt;.
        /// </summary>
        public static string GeneratedStatus {
            get {
                return ResourceManager.GetString("GeneratedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to href.
        /// </summary>
        public static string href {
            get {
                return ResourceManager.GetString("href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Factura.
        /// </summary>
        public static string InvoiceNumberColumn {
            get {
                return ResourceManager.GetString("InvoiceNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Caja/ListarFacturas.aspx?Id=.
        /// </summary>
        public static string invoicesURL {
            get {
                return ResourceManager.GetString("invoicesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Caja/VerDetalleFactura.aspx?Id=.
        /// </summary>
        public static string invoiceURL {
            get {
                return ResourceManager.GetString("invoiceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iva.
        /// </summary>
        public static string IVAColumn {
            get {
                return ResourceManager.GetString("IVAColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha cargado la tabla de ordenes cerradas satisfactoriamente.
        /// </summary>
        public static string MessageGetClosedOrders {
            get {
                return ResourceManager.GetString("MessageGetClosedOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al llenar la tabla de Ordenes cerradas.
        /// </summary>
        public static string MessageMVPExceptionClosedOrdersTable {
            get {
                return ResourceManager.GetString("MessageMVPExceptionClosedOrdersTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BO-04-001.
        /// </summary>
        public static string MVPExceptionClosedOrdersTableCode {
            get {
                return ResourceManager.GetString("MVPExceptionClosedOrdersTableCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Orden.
        /// </summary>
        public static string OrderNumberColumn {
            get {
                return ResourceManager.GetString("OrderNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Mesa.
        /// </summary>
        public static string OrderTableColumn {
            get {
                return ResourceManager.GetString("OrderTableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string OrderUserColumn {
            get {
                return ResourceManager.GetString("OrderUserColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio por plato.
        /// </summary>
        public static string PriceColumn {
            get {
                return ResourceManager.GetString("PriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string QuantityColumn {
            get {
                return ResourceManager.GetString("QuantityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountID.
        /// </summary>
        public static string SessionIdAccount {
            get {
                return ResourceManager.GetString("SessionIdAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceId.
        /// </summary>
        public static string SessionIdInvoice {
            get {
                return ResourceManager.GetString("SessionIdInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameRestaurant.
        /// </summary>
        public static string SessionNameRest {
            get {
                return ResourceManager.GetString("SessionNameRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountNumber.
        /// </summary>
        public static string SessionNumberAccount {
            get {
                return ResourceManager.GetString("SessionNumberAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceNumber.
        /// </summary>
        public static string SessionNumberInvoice {
            get {
                return ResourceManager.GetString("SessionNumberInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantID.
        /// </summary>
        public static string SessionRestaurantId {
            get {
                return ResourceManager.GetString("SessionRestaurantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string StatusColumn {
            get {
                return ResourceManager.GetString("StatusColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TotalColumn {
            get {
                return ResourceManager.GetString("TotalColumn", resourceCulture);
            }
        }
    }
}
