//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficePresenter.Login {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceLogin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLogin() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOfficePresenter.Login.ResourceLogin", typeof(ResourceLogin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lastname.
        /// </summary>
        public static string sessionLastname {
            get {
                return ResourceManager.GetString("sessionLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a name.
        /// </summary>
        public static string sessionName {
            get {
                return ResourceManager.GetString("sessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a restaurantName.
        /// </summary>
        public static string SessionNameRest {
            get {
                return ResourceManager.GetString("SessionNameRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idRestaurante.
        /// </summary>
        public static string SessionRestaurant {
            get {
                return ResourceManager.GetString("SessionRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RestaurantID.
        /// </summary>
        public static string sessionRestaurantID {
            get {
                return ResourceManager.GetString("sessionRestaurantID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        public static string sessionRol {
            get {
                return ResourceManager.GetString("sessionRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a userID.
        /// </summary>
        public static string sessionUserID {
            get {
                return ResourceManager.GetString("sessionUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a userName.
        /// </summary>
        public static string sessionUserName {
            get {
                return ResourceManager.GetString("sessionUserName", resourceCulture);
            }
        }
    }
}
