//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.ds201625.fonda.DataAccess.Exceptions.Restaurant {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceRestaurantMessagesDAO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceRestaurantMessagesDAO() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.ds201625.fonda.DataAccess.Exceptions.Restaurant.ResourceRestaurantMessagesDAO" +
                            "", typeof(ResourceRestaurantMessagesDAO).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar el objeto categoria.
        /// </summary>
        internal static string AddCategoryFondaDAOException {
            get {
                return ResourceManager.GetString("AddCategoryFondaDAOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al generar el objeto restaurante.
        /// </summary>
        internal static string GenerateRestaurantFondaDAOException {
            get {
                return ResourceManager.GetString("GenerateRestaurantFondaDAOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar todas las categorias de la base de datos.
        /// </summary>
        internal static string GetAllCategoriesFondaDAOException {
            get {
                return ResourceManager.GetString("GetAllCategoriesFondaDAOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar todas las currencies de la base de datos.
        /// </summary>
        internal static string GetAllCurrenciesFondaDAOException {
            get {
                return ResourceManager.GetString("GetAllCurrenciesFondaDAOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar todas las zonas de la base de datos.
        /// </summary>
        internal static string GetAllZonesFondaDAOException {
            get {
                return ResourceManager.GetString("GetAllZonesFondaDAOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al modificar el objeto categoria.
        /// </summary>
        internal static string ModifyCategoryFondaDAOException {
            get {
                return ResourceManager.GetString("ModifyCategoryFondaDAOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al modificar el objeto restaurante.
        /// </summary>
        internal static string ModifyRestaurantFondaDAOException {
            get {
                return ResourceManager.GetString("ModifyRestaurantFondaDAOException", resourceCulture);
            }
        }
    }
}
