//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.ds201625.fonda.DataAccess {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMessagesDAO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesDAO() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.ds201625.fonda.DataAccess.ResourceMessagesDAO", typeof(ResourceMessagesDAO).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar un objeto de la entidad: .
        /// </summary>
        internal static string DeleteEntityFondaDAOException {
            get {
                return ResourceManager.GetString("DeleteEntityFondaDAOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al consultar lista de entidades.
        /// </summary>
        internal static string FindAllFondaDAOException {
            get {
                return ResourceManager.GetString("FindAllFondaDAOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al consultar un useraccount por su email: .
        /// </summary>
        internal static string FindByEmailUserAccountFondaDAOException {
            get {
                return ResourceManager.GetString("FindByEmailUserAccountFondaDAOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al consultar una entidad por la propiedad: .
        /// </summary>
        internal static string FindByFondaDAOExceptionProperty {
            get {
                return ResourceManager.GetString("FindByFondaDAOExceptionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a y el valor.
        /// </summary>
        internal static string FindByFondaDAOExceptionValue {
            get {
                return ResourceManager.GetString("FindByFondaDAOExceptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al consultar por el Id: .
        /// </summary>
        internal static string FindByIdFondaDAOException {
            get {
                return ResourceManager.GetString("FindByIdFondaDAOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al buscar un token por su strToken: .
        /// </summary>
        internal static string FindByStrTokenException {
            get {
                return ResourceManager.GetString("FindByStrTokenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar un objeto de la entidad: .
        /// </summary>
        internal static string SaveEntityFondaDAOException {
            get {
                return ResourceManager.GetString("SaveEntityFondaDAOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al consultar una entidad por su Id: .
        /// </summary>
        internal static string String1FindByIdFondaDAOException {
            get {
                return ResourceManager.GetString("String1FindByIdFondaDAOException", resourceCulture);
            }
        }
    }
}
