//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.ds201625.fonda.Resources.FondaResources.Login {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.ds201625.fonda.Resources.FondaResources.Login.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando para obtener todos los empleados..
        /// </summary>
        public static string ClassNameGetEmployee {
            get {
                return ResourceManager.GetString("ClassNameGetEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando para obtener un empleado por su id..
        /// </summary>
        public static string ClassNameGetEmployeeId {
            get {
                return ResourceManager.GetString("ClassNameGetEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando para obtener un empleado por su cuenta de usuario..
        /// </summary>
        public static string ClassNameGetEmployeeUser {
            get {
                return ResourceManager.GetString("ClassNameGetEmployeeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando para obtener un empleado por su ssn..
        /// </summary>
        public static string ClassNameGetExployeeSsn {
            get {
                return ResourceManager.GetString("ClassNameGetExployeeSsn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando para obtener todos los restaurantes..
        /// </summary>
        public static string ClassNameGetRestaurantAll {
            get {
                return ResourceManager.GetString("ClassNameGetRestaurantAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando para obtener un restaurante por su id..
        /// </summary>
        public static string ClassNameGetRestaurantId {
            get {
                return ResourceManager.GetString("ClassNameGetRestaurantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando para obtener todos los roles..
        /// </summary>
        public static string ClassNameGetRoles {
            get {
                return ResourceManager.GetString("ClassNameGetRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando para obtener una cuenta de usuario por su correo electronico.
        /// </summary>
        public static string ClassNameGetUserAccountEmail {
            get {
                return ResourceManager.GetString("ClassNameGetUserAccountEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepcion fuera del rango del parametro..
        /// </summary>
        public static string ClassNameIndexParameter {
            get {
                return ResourceManager.GetString("ClassNameIndexParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepcion para parametro invalido..
        /// </summary>
        public static string ClassNameInvalidParameter {
            get {
                return ResourceManager.GetString("ClassNameInvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepcion para pametro no encontrado..
        /// </summary>
        public static string ClassNameParameterNotFound {
            get {
                return ResourceManager.GetString("ClassNameParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando para guardar un empleado..
        /// </summary>
        public static string ClassNameSaveEmployee {
            get {
                return ResourceManager.GetString("ClassNameSaveEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metodo disparador del Error para Comando..
        /// </summary>
        public static string CommandMethod {
            get {
                return ResourceManager.GetString("CommandMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha finalizado el logger.
        /// </summary>
        public static string EndLogger {
            get {
                return ResourceManager.GetString("EndLogger", resourceCulture);
            }
        }
    }
}
