//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FondaResources.Login {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FondaResources.Login.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CommandGetAllEmployee.
        /// </summary>
        public static string ClassNameGetEmployee {
            get {
                return ResourceManager.GetString("ClassNameGetEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CommandGetEmployeeById.
        /// </summary>
        public static string ClassNameGetEmployeeId {
            get {
                return ResourceManager.GetString("ClassNameGetEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CommandGetEmployeeBySsn.
        /// </summary>
        public static string ClassNameGetExployeeSsn {
            get {
                return ResourceManager.GetString("ClassNameGetExployeeSsn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CommandGetRestaurantById.
        /// </summary>
        public static string ClassNameGetRestaurant {
            get {
                return ResourceManager.GetString("ClassNameGetRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CommandGetRestaurantAll.
        /// </summary>
        public static string ClassNameGetRestaurantAll {
            get {
                return ResourceManager.GetString("ClassNameGetRestaurantAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CommandGetAllRoles.
        /// </summary>
        public static string ClassNameGetRoles {
            get {
                return ResourceManager.GetString("ClassNameGetRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CommandGetUserAccoundByEmail.
        /// </summary>
        public static string ClassNameGetUserAccountEmail {
            get {
                return ResourceManager.GetString("ClassNameGetUserAccountEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CommandSaveEmployee.
        /// </summary>
        public static string ClassNameSaveEmployee {
            get {
                return ResourceManager.GetString("ClassNameSaveEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execute.
        /// </summary>
        public static string CommandMethod {
            get {
                return ResourceManager.GetString("CommandMethod", resourceCulture);
            }
        }
    }
}
