//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FondaResources.Login {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class G1RecursosInterfaz {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal G1RecursosInterfaz() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FondaResources.Login.G1RecursosInterfaz", typeof(G1RecursosInterfaz).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;asp:LinkButton runat=&quot;server&quot; onclick=&quot;Modificar_Click&quot; data-id=&quot;12345&quot;&gt;&lt;i class=&quot;fa fa-pencil&quot;&gt;&lt;/i&gt;&lt;/asp:LinkButton&gt;&lt;asp:LinkButton runat=&quot;server&quot; onclick=&quot;Modificar_Click&quot; data-id=&quot;12345&quot;&gt;&lt;i class=&quot;fa fa-check&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt;&lt;/asp:LinkButton&gt;&lt;asp:LinkButton runat=&quot;server&quot; onclick=&quot;Modificar_Click&quot; data-id=&quot;12345&quot;&gt;&lt;i class=&quot;fa fa-times&quot;&gt;&lt;/i&gt;&lt;/asp:LinkButton&gt;.
        /// </summary>
        public static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a alert alert-success alert-dismissible.
        /// </summary>
        public static string alertaSuccess {
            get {
                return ResourceManager.GetString("alertaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a class.
        /// </summary>
        public static string alertClase {
            get {
                return ResourceManager.GetString("alertClase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a role.
        /// </summary>
        public static string alertRole {
            get {
                return ResourceManager.GetString("alertRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;button type=&quot;button&quot; class=&quot;close&quot; data-dismiss=&quot;alert&quot; aria-hidden=&quot;true&quot; onclick=&quot;ClearAlert&quot;&gt;&amp;times;&lt;/button&gt;.
        /// </summary>
        public static string buttonAlert {
            get {
                return ResourceManager.GetString("buttonAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;button type=&quot;button&quot; data-dismiss=&quot;alert&quot; aria-hidden=&quot;true&quot;&gt;&amp;times;&lt;/button&gt;.
        /// </summary>
        public static string buttonAlert2 {
            get {
                return ResourceManager.GetString("buttonAlert2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a alert alert-danger alert-dismissable col-lg-12.
        /// </summary>
        public static string danger {
            get {
                return ResourceManager.GetString("danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;i class=&quot;fa fa-pencil&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;i class=&quot;fa fa-check&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string editstatusA {
            get {
                return ResourceManager.GetString("editstatusA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;i class=&quot;fa fa-times&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string editstatusI {
            get {
                return ResourceManager.GetString("editstatusI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;i class=&quot;fa fa-ban&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string iconDanger {
            get {
                return ResourceManager.GetString("iconDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;i class=&quot;fa fa-exclamation-circle&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string iconExclamation {
            get {
                return ResourceManager.GetString("iconExclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;i class=&quot;fa fa-check&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string iconSuccess {
            get {
                return ResourceManager.GetString("iconSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;span class=&quot;label label-success&quot;&gt;&lt;i class=&quot;fa fa-check&quot;&gt;&lt;/i&gt;&lt;/span&gt;.
        /// </summary>
        public static string statusA {
            get {
                return ResourceManager.GetString("statusA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;span class=&quot;label label-danger&quot;&gt;&lt;i class=&quot;fa fa-times&quot;&gt;&lt;/i&gt;&lt;/span&gt;.
        /// </summary>
        public static string statusI {
            get {
                return ResourceManager.GetString("statusI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;strong&gt; Cancelada!&lt;/strong&gt;.
        /// </summary>
        public static string strogCancel {
            get {
                return ResourceManager.GetString("strogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;strong&gt; Agregado!&lt;/strong&gt;&quot;.
        /// </summary>
        public static string strongAdd {
            get {
                return ResourceManager.GetString("strongAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;strong&gt; Error&lt;/strong&gt;.
        /// </summary>
        public static string strongError {
            get {
                return ResourceManager.GetString("strongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;strong&gt; Modificado!&lt;/strong&gt;&quot;.
        /// </summary>
        public static string strongModify {
            get {
                return ResourceManager.GetString("strongModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;strong&gt; No &lt;/strong&gt;.
        /// </summary>
        public static string strongNot {
            get {
                return ResourceManager.GetString("strongNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a alert alert-success fade in alert-dismissable.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
    }
}
