//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.ds201625.fonda.Resources.FondaResources.Login {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class G1RecursosInterfaz {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal G1RecursosInterfaz() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.ds201625.fonda.Resources.FondaResources.Login.G1RecursosInterfaz", typeof(G1RecursosInterfaz).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;asp:LinkButton runat=&quot;server&quot; onclick=&quot;Modificar_Click&quot; data-id=&quot;12345&quot;&gt;&lt;i class=&quot;fa fa-pencil&quot;&gt;&lt;/i&gt;&lt;/asp:LinkButton&gt;&lt;asp:LinkButton runat=&quot;server&quot; onclick=&quot;Modificar_Click&quot; data-id=&quot;12345&quot;&gt;&lt;i class=&quot;fa fa-check&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt;&lt;/asp:LinkButton&gt;&lt;asp:LinkButton runat=&quot;server&quot; onclick=&quot;Modificar_Click&quot; data-id=&quot;12345&quot;&gt;&lt;i class=&quot;fa fa-times&quot;&gt;&lt;/i&gt;&lt;/asp:LinkButton&gt;.
        /// </summary>
        public static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-success alert-dismissible.
        /// </summary>
        public static string alertaSuccess {
            get {
                return ResourceManager.GetString("alertaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        public static string alertClase {
            get {
                return ResourceManager.GetString("alertClase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role.
        /// </summary>
        public static string alertRole {
            get {
                return ResourceManager.GetString("alertRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;button type=&quot;button&quot; class=&quot;close&quot; data-dismiss=&quot;alert&quot; aria-hidden=&quot;true&quot; onclick=&quot;ClearAlert&quot;&gt;&amp;times;&lt;/button&gt;.
        /// </summary>
        public static string buttonAlert {
            get {
                return ResourceManager.GetString("buttonAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;button type=&quot;button&quot; data-dismiss=&quot;alert&quot; aria-hidden=&quot;true&quot;&gt;&amp;times;&lt;/button&gt;.
        /// </summary>
        public static string buttonAlert2 {
            get {
                return ResourceManager.GetString("buttonAlert2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-danger alert-dismissable col-lg-12.
        /// </summary>
        public static string danger {
            get {
                return ResourceManager.GetString("danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-pencil&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-check&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string editstatusA {
            get {
                return ResourceManager.GetString("editstatusA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-times&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string editstatusI {
            get {
                return ResourceManager.GetString("editstatusI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-ban&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string iconDanger {
            get {
                return ResourceManager.GetString("iconDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-exclamation-circle&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string iconExclamation {
            get {
                return ResourceManager.GetString("iconExclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-check&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string iconSuccess {
            get {
                return ResourceManager.GetString("iconSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-success&quot;&gt;&lt;i class=&quot;fa fa-check&quot;&gt;&lt;/i&gt;&lt;/span&gt;.
        /// </summary>
        public static string statusA {
            get {
                return ResourceManager.GetString("statusA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;label label-danger&quot;&gt;&lt;i class=&quot;fa fa-times&quot;&gt;&lt;/i&gt;&lt;/span&gt;.
        /// </summary>
        public static string statusI {
            get {
                return ResourceManager.GetString("statusI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt; Cancelada!&lt;/strong&gt;.
        /// </summary>
        public static string strogCancel {
            get {
                return ResourceManager.GetString("strogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt; Agregado!&lt;/strong&gt;&quot;.
        /// </summary>
        public static string strongAdd {
            get {
                return ResourceManager.GetString("strongAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt; Error&lt;/strong&gt;.
        /// </summary>
        public static string strongError {
            get {
                return ResourceManager.GetString("strongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt; Modificado!&lt;/strong&gt;&quot;.
        /// </summary>
        public static string strongModify {
            get {
                return ResourceManager.GetString("strongModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt; No &lt;/strong&gt;.
        /// </summary>
        public static string strongNot {
            get {
                return ResourceManager.GetString("strongNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert alert-success fade in alert-dismissable.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
    }
}
