//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FondaBeckEndLogic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FondaBeckEndLogic.ResourceMessages", typeof(ResourceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar un restaurante favorito del comensal.
        /// </summary>
        internal static string AddFavRestException {
            get {
                return ResourceManager.GetString("AddFavRestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar un perfil de un comensal.
        /// </summary>
        internal static string AddProfileException {
            get {
                return ResourceManager.GetString("AddProfileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha iniciado el logger.
        /// </summary>
        internal static string BeginLogger {
            get {
                return ResourceManager.GetString("BeginLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandSaveEmployee.
        /// </summary>
        internal static string ClassNameSaveEmployee {
            get {
                return ResourceManager.GetString("ClassNameSaveEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commensal: .
        /// </summary>
        internal static string Commensal {
            get {
                return ResourceManager.GetString("Commensal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email del comensal.
        /// </summary>
        internal static string CommensalEmail {
            get {
                return ResourceManager.GetString("CommensalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservacion del comensal.
        /// </summary>
        internal static string CommensalReservation {
            get {
                return ResourceManager.GetString("CommensalReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear un Commensal.
        /// </summary>
        internal static string CreateCommensalException {
            get {
                return ResourceManager.GetString("CreateCommensalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar una reservacion al comensal.
        /// </summary>
        internal static string CreateCommensalReservationException {
            get {
                return ResourceManager.GetString("CreateCommensalReservationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar un restaurante favorito del comensal.
        /// </summary>
        internal static string DeleteFavRestException {
            get {
                return ResourceManager.GetString("DeleteFavRestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar un perfil de un comensal.
        /// </summary>
        internal static string DeleteProfileException {
            get {
                return ResourceManager.GetString("DeleteProfileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error eliminar el Token de un Commensal.
        /// </summary>
        internal static string DeleteTokenException {
            get {
                return ResourceManager.GetString("DeleteTokenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha finalizado el logger.
        /// </summary>
        internal static string EndLogger {
            get {
                return ResourceManager.GetString("EndLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurante favorito del comensal .
        /// </summary>
        internal static string FavoriteRestaurant {
            get {
                return ResourceManager.GetString("FavoriteRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener la lista de restaurant para elegir los favoritos del comensal.
        /// </summary>
        internal static string GetAllRestaurantException {
            get {
                return ResourceManager.GetString("GetAllRestaurantException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el comensal por email.
        /// </summary>
        internal static string GetCommensalEmailException {
            get {
                return ResourceManager.GetString("GetCommensalEmailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar un commensal.
        /// </summary>
        internal static string GetCommensalException {
            get {
                return ResourceManager.GetString("GetCommensalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar los restaurantes favoritos del comensal.
        /// </summary>
        internal static string GetFavoriteRestaurant {
            get {
                return ResourceManager.GetString("GetFavoriteRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar los restaurantes favoritos del comensal.
        /// </summary>
        internal static string GetFavoriteRestaurantException {
            get {
                return ResourceManager.GetString("GetFavoriteRestaurantException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Perfil de un Commensal.
        /// </summary>
        internal static string GetProfileException {
            get {
                return ResourceManager.GetString("GetProfileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener la lista de restaurant para elegir los favoritos del comensal.
        /// </summary>
        internal static string GetRestFavException {
            get {
                return ResourceManager.GetString("GetRestFavException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Token de un Commensal.
        /// </summary>
        internal static string GetTokenException {
            get {
                return ResourceManager.GetString("GetTokenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el userAccount.
        /// </summary>
        internal static string GetUserException {
            get {
                return ResourceManager.GetString("GetUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Invalidos.
        /// </summary>
        internal static string InvalidInformation {
            get {
                return ResourceManager.GetString("InvalidInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del Perfil Invalidos.
        /// </summary>
        internal static string InvalidInformationProfile {
            get {
                return ResourceManager.GetString("InvalidInformationProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros iválidos al intentar agregar un restaurante a favoritos.
        /// </summary>
        internal static string ParametersAddFavRestException {
            get {
                return ResourceManager.GetString("ParametersAddFavRestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros iválidos al intentar agregar una reservacion al commensal.
        /// </summary>
        internal static string ParametersCreateCommensalReservationException {
            get {
                return ResourceManager.GetString("ParametersCreateCommensalReservationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros iválidos al intentar eliminar un restaurant favorito.
        /// </summary>
        internal static string ParametersDeleteFavRestException {
            get {
                return ResourceManager.GetString("ParametersDeleteFavRestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros iválidos al intentar obtener los restaurantes disponibles.
        /// </summary>
        internal static string ParametersGetAllRestException {
            get {
                return ResourceManager.GetString("ParametersGetAllRestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros iválidos al intentar obtener el email de un comensal.
        /// </summary>
        internal static string ParametersGetComensEmailException {
            get {
                return ResourceManager.GetString("ParametersGetComensEmailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros iválidos al intentar obtener los restaurantes favoritos del comensal.
        /// </summary>
        internal static string ParametersGetFavRestException {
            get {
                return ResourceManager.GetString("ParametersGetFavRestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil del Commensal: .
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Agregado al Commensal: .
        /// </summary>
        internal static string ProfileAdded {
            get {
                return ResourceManager.GetString("ProfileAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Eliminado de un Commensal: .
        /// </summary>
        internal static string ProfileDeleted {
            get {
                return ResourceManager.GetString("ProfileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Modificado de un Commensal: .
        /// </summary>
        internal static string ProfileUpdated {
            get {
                return ResourceManager.GetString("ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservacion Agregada al Commensal:.
        /// </summary>
        internal static string ReservationAdded {
            get {
                return ResourceManager.GetString("ReservationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurante Agregado a Favoritos: .
        /// </summary>
        internal static string RestAddedToFav {
            get {
                return ResourceManager.GetString("RestAddedToFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria de Restaurante.
        /// </summary>
        internal static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurante Eliminado de Favoritos: .
        /// </summary>
        internal static string RestDeletedFromFav {
            get {
                return ResourceManager.GetString("RestDeletedFromFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string Slash {
            get {
                return ResourceManager.GetString("Slash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token del Commensal: .
        /// </summary>
        internal static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al modificar un perfil de un comensal.
        /// </summary>
        internal static string UpdateProfileException {
            get {
                return ResourceManager.GetString("UpdateProfileException", resourceCulture);
            }
        }
    }
}
