//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FondaBeckEndLogic {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FondaBeckEndLogic.ResourceMessages", typeof(ResourceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al agregar un restaurante favorito del comensal.
        /// </summary>
        internal static string AddFavRestException {
            get {
                return ResourceManager.GetString("AddFavRestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha iniciado el logger.
        /// </summary>
        internal static string BeginLogger {
            get {
                return ResourceManager.GetString("BeginLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CommandSaveEmployee.
        /// </summary>
        internal static string ClassNameSaveEmployee {
            get {
                return ResourceManager.GetString("ClassNameSaveEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email del comensal.
        /// </summary>
        internal static string CommensalEmail {
            get {
                return ResourceManager.GetString("CommensalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar un restaurante favorito del comensal.
        /// </summary>
        internal static string DeleteFavRestException {
            get {
                return ResourceManager.GetString("DeleteFavRestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha finalizado el logger.
        /// </summary>
        internal static string EndLogger {
            get {
                return ResourceManager.GetString("EndLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restaurante favorito del comensal .
        /// </summary>
        internal static string FavoriteRestaurant {
            get {
                return ResourceManager.GetString("FavoriteRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al buscar el comensal por email.
        /// </summary>
        internal static string GetCommensalEmailException {
            get {
                return ResourceManager.GetString("GetCommensalEmailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al buscar los restaurantes favoritos del comensal.
        /// </summary>
        internal static string GetFavoriteRestaurant {
            get {
                return ResourceManager.GetString("GetFavoriteRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener la lista de restaurant para elegir los favoritos del comensal.
        /// </summary>
        internal static string GetRestFavException {
            get {
                return ResourceManager.GetString("GetRestFavException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Invalidos.
        /// </summary>
        internal static string InvalidInformation {
            get {
                return ResourceManager.GetString("InvalidInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restaurante Agregado a Favoritos: .
        /// </summary>
        internal static string RestAddedToFav {
            get {
                return ResourceManager.GetString("RestAddedToFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoria de Restaurante.
        /// </summary>
        internal static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restaurante Eliminado de Favoritos: .
        /// </summary>
        internal static string RestDeletedFromFav {
            get {
                return ResourceManager.GetString("RestDeletedFromFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /.
        /// </summary>
        internal static string Slash {
            get {
                return ResourceManager.GetString("Slash", resourceCulture);
            }
        }
    }
}
