//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.Seccion.Caja {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCaja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCaja() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.Seccion.Caja.ResourceCaja", typeof(ResourceCaja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-money fa-fw&quot;&gt;&lt;/i&gt;.
        /// </summary>
        internal static string Action2Account {
            get {
                return ResourceManager.GetString("Action2Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-pencil-square-o&quot;&gt;&lt;/i&gt;.
        /// </summary>
        internal static string Action3Account {
            get {
                return ResourceManager.GetString("Action3Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-info-circle&quot;&gt;&lt;/i&gt;.
        /// </summary>
        internal static string ActionAccount {
            get {
                return ResourceManager.GetString("ActionAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-check&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt;.
        /// </summary>
        internal static string ActionCheckStatus {
            get {
                return ResourceManager.GetString("ActionCheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-times&quot;&gt;&lt;/i&gt;.
        /// </summary>
        internal static string ActionUnCheckStatus {
            get {
                return ResourceManager.GetString("ActionUnCheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td class=&quot;text-center&quot;&gt;&lt;span class=&quot;label label-success&quot;&gt;&lt;i class=&quot;fa fa-check&quot;&gt;&lt;p class=&quot;stat&quot;&gt;A&lt;/p&gt;&lt;/i&gt;&lt;/span&gt;&lt;/td&gt;.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input runat=&quot;server&quot; type=&quot;number&quot; name=&quot;quantity&quot; min=&quot;1&quot; max=&quot;10&quot; value=1 /&gt;.
        /// </summary>
        internal static string AgregarCantidadOrden {
            get {
                return ResourceManager.GetString("AgregarCantidadOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&gt;.
        /// </summary>
        internal static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/a&gt;.
        /// </summary>
        internal static string Cerrar2 {
            get {
                return ResourceManager.GetString("Cerrar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input runat=&quot;server&quot; type=&quot;checkbox&quot; /&gt;.
        /// </summary>
        internal static string CheckBoxAgregar {
            get {
                return ResourceManager.GetString("CheckBoxAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td class=&quot;text-center&quot;&gt;&lt;span class=&quot;label label-danger&quot;&gt;&lt;i class=&quot;fa fa-times&quot;&gt;&lt;p class=&quot;stat&quot;&gt;I&lt;/p&gt;&lt;/i&gt;&lt;/span&gt;&lt;/td&gt;.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a runat=&quot;server&quot; href=&quot;/Seccion/Caja/ModificarOrden.aspx?id=.
        /// </summary>
        internal static string ModificarFactura {
            get {
                return ResourceManager.GetString("ModificarFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-pencil-square-o&quot;&gt;&lt;/i&gt;.
        /// </summary>
        internal static string ModificarFactura2 {
            get {
                return ResourceManager.GetString("ModificarFactura2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a runat=&quot;server&quot; href=&quot;/Seccion/Caja/VerFactura.aspx?id=.
        /// </summary>
        internal static string VerDetalleFactura {
            get {
                return ResourceManager.GetString("VerDetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-info-circle&quot;&gt;&lt;/i&gt;.
        /// </summary>
        internal static string VerDetalleFactura2 {
            get {
                return ResourceManager.GetString("VerDetalleFactura2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a runat=&quot;server&quot; href=&quot;/Seccion/Caja/VerDetalleOrden.aspx?id=.
        /// </summary>
        internal static string VerDetalleOrden {
            get {
                return ResourceManager.GetString("VerDetalleOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-info-circle&quot;&gt;&lt;/i&gt;.
        /// </summary>
        internal static string VerDetalleOrden2 {
            get {
                return ResourceManager.GetString("VerDetalleOrden2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a runat=&quot;server&quot; href=&quot;/Seccion/Caja/CrearFactura.aspx?id=.
        /// </summary>
        internal static string VerFactura {
            get {
                return ResourceManager.GetString("VerFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-money fa-fw&quot;&gt;&lt;/i&gt;.
        /// </summary>
        internal static string VerFactura2 {
            get {
                return ResourceManager.GetString("VerFactura2", resourceCulture);
            }
        }
    }
}
