//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.Seccion.Configuracion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class G1RecursosInterfaz {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal G1RecursosInterfaz() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.Seccion.Configuracion.G1RecursosInterfaz", typeof(G1RecursosInterfaz).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a alert alert-success alert-dismissible.
        /// </summary>
        internal static string alertaSuccess {
            get {
                return ResourceManager.GetString("alertaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a class.
        /// </summary>
        internal static string alertClase {
            get {
                return ResourceManager.GetString("alertClase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a role.
        /// </summary>
        internal static string alertRole {
            get {
                return ResourceManager.GetString("alertRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a alert alert-danger alert-dismissable col-lg-12.
        /// </summary>
        internal static string danger {
            get {
                return ResourceManager.GetString("danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;strong&gt;No se ha Modificado!&lt;/strong&gt;&quot;.
        /// </summary>
        internal static string dangerModificacionFinal {
            get {
                return ResourceManager.GetString("dangerModificacionFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;&lt;a href=&apos;#&apos; class=&apos;close&apos; data-dismiss=&apos;alert&apos; aria-label=&apos;close&apos;&gt;&amp;times;&lt;/a&gt;.
        /// </summary>
        internal static string dangerModificacioninicio {
            get {
                return ResourceManager.GetString("dangerModificacioninicio", resourceCulture);
            }
        }
    }
}
