//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.ds201625.fonda.BackEnd {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.ds201625.fonda.BackEnd.GeneralRes", typeof(GeneralRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar un restaurante favorito del comensal.
        /// </summary>
        internal static string AddFavRestException {
            get {
                return ResourceManager.GetString("AddFavRestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string BasicAuthSheme {
            get {
                return ResourceManager.GetString("BasicAuthSheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha iniciado el Logger.
        /// </summary>
        internal static string BeginLogger {
            get {
                return ResourceManager.GetString("BeginLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email del comensal.
        /// </summary>
        internal static string CommensalEmail {
            get {
                return ResourceManager.GetString("CommensalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string CommensalIDHeader {
            get {
                return ResourceManager.GetString("CommensalIDHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar restaurant favorito de un comensal.
        /// </summary>
        internal static string DeleteFavRestException {
            get {
                return ResourceManager.GetString("DeleteFavRestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha finalizado el logger.
        /// </summary>
        internal static string EndLogger {
            get {
                return ResourceManager.GetString("EndLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurante favorito del comensal .
        /// </summary>
        internal static string FavoriteRestaurant {
            get {
                return ResourceManager.GetString("FavoriteRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonda.
        /// </summary>
        internal static string FondaAuthSheme {
            get {
                return ResourceManager.GetString("FondaAuthSheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el comensal por email.
        /// </summary>
        internal static string GetCommensalEmailException {
            get {
                return ResourceManager.GetString("GetCommensalEmailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener la lista de los restaurantes favoritos del comensal.
        /// </summary>
        internal static string GetFavoriteRestaurant {
            get {
                return ResourceManager.GetString("GetFavoriteRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener la lista de restaurant para elegir los favoritos del comensal.
        /// </summary>
        internal static string GetRestFavException {
            get {
                return ResourceManager.GetString("GetRestFavException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Invalidos.
        /// </summary>
        internal static string InvalidInformation {
            get {
                return ResourceManager.GetString("InvalidInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurante Agregado a Favoritos: .
        /// </summary>
        internal static string RestAddedToFav {
            get {
                return ResourceManager.GetString("RestAddedToFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria de Restaurante.
        /// </summary>
        internal static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string RestaurantIDHeader {
            get {
                return ResourceManager.GetString("RestaurantIDHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurante Eliminado de Favoritos: .
        /// </summary>
        internal static string RestDeletedFromFav {
            get {
                return ResourceManager.GetString("RestDeletedFromFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string Slash {
            get {
                return ResourceManager.GetString("Slash", resourceCulture);
            }
        }
    }
}
