//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.ds201625.fonda.Resources.FondaResources.Reservation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReservationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReservationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.ds201625.fonda.Resources.FondaResources.Reservation.ReservationResources", typeof(ReservationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string ActionColumn {
            get {
                return ResourceManager.GetString("ActionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelada.
        /// </summary>
        public static string CanceledReservationStatus {
            get {
                return ResourceManager.GetString("CanceledReservationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservacion Cancelada.
        /// </summary>
        public static string CanceledReservationStatusDes {
            get {
                return ResourceManager.GetString("CanceledReservationStatusDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-times&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string CancelReservation {
            get {
                return ResourceManager.GetString("CancelReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReservationsPresenter.
        /// </summary>
        public static string ClassNameReservationsPresenter {
            get {
                return ResourceManager.GetString("ClassNameReservationsPresenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-center.
        /// </summary>
        public static string CssClassActions {
            get {
                return ResourceManager.GetString("CssClassActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data-id.
        /// </summary>
        public static string dataId {
            get {
                return ResourceManager.GetString("dataId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to href.
        /// </summary>
        public static string href {
            get {
                return ResourceManager.GetString("href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha cargado la tabla de reservaciones satisfactoriamente.
        /// </summary>
        public static string MessageGetReservations {
            get {
                return ResourceManager.GetString("MessageGetReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Reservas/ListarReservas.aspx?Id=.
        /// </summary>
        public static string RefreshURL {
            get {
                return ResourceManager.GetString("RefreshURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Comensales.
        /// </summary>
        public static string ReservationCommensalNumberColumn {
            get {
                return ResourceManager.GetString("ReservationCommensalNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de creacion.
        /// </summary>
        public static string ReservationCreationDateColumn {
            get {
                return ResourceManager.GetString("ReservationCreationDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de reservacion.
        /// </summary>
        public static string ReservationDateColumn {
            get {
                return ResourceManager.GetString("ReservationDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-info-circle&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string ReservationInfo {
            get {
                return ResourceManager.GetString("ReservationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Reservacion.
        /// </summary>
        public static string ReservationNumberColumn {
            get {
                return ResourceManager.GetString("ReservationNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Mesa.
        /// </summary>
        public static string ReservationTableColumn {
            get {
                return ResourceManager.GetString("ReservationTableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Reservas/VerDetalleReserva.aspx?Id=.
        /// </summary>
        public static string reservationURL {
            get {
                return ResourceManager.GetString("reservationURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string ReservationUserColumn {
            get {
                return ResourceManager.GetString("ReservationUserColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservada.
        /// </summary>
        public static string ReservedReservationStatus {
            get {
                return ResourceManager.GetString("ReservedReservationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservacion Realizada.
        /// </summary>
        public static string ReservedReservationStatusDes {
            get {
                return ResourceManager.GetString("ReservedReservationStatusDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los Restaurantes.
        /// </summary>
        public static string SessionAllRestaurants {
            get {
                return ResourceManager.GetString("SessionAllRestaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReservationID.
        /// </summary>
        public static string SessionIdReservation {
            get {
                return ResourceManager.GetString("SessionIdReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameRestaurant.
        /// </summary>
        public static string SessionNameRest {
            get {
                return ResourceManager.GetString("SessionNameRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReservationNumber.
        /// </summary>
        public static string SessionNumberReservation {
            get {
                return ResourceManager.GetString("SessionNumberReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string StatusColumn {
            get {
                return ResourceManager.GetString("StatusColumn", resourceCulture);
            }
        }
    }
}
